[build]
builder = "dockerfile"

[deploy]
startCommand = "apache2-foreground"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
MYSQL_HOST = "${{MYSQL_PRIVATE_URL}}"
MYSQL_DATABASE = "examsys"
MYSQL_USER = "examsys"
MYSQL_PASSWORD = "${{MYSQL_PASSWORD}}"
APACHE_DOCUMENT_ROOT = "/var/www/public"